### ISSUE TITLE
listtransactions does not return all transactions

### ISSUE THREAD

**Issue by Liam-Dow** [particl/testnet#10]
Seem to have come into an issue. I sent a large number of transactions, about 10 per second for a couple of minutes. When I do the command:
`particl-cli listtransactions`

I only see a small amount of these transactions. Many of them fell into Block 339, 340 and 341 and some likely still to be confirmed. See screenshot below of terminal.
![screen shot 2017-06-08 at 21 25 52](https://user-images.githubusercontent.com/29288449/26949472-fb404c24-4c91-11e7-8f7a-55ab04057048.png)

Unfortunately I didn't get the output for hundreds of the txids, which would have made it easier to understand. The amounts of part I was sending 0.001 was very small, so should definitley still have the majority in my balance. I sent all the transactions to pZ41zhDbKec47Wxe9NLHhUwJR2jquNeGt1 which is an address I chose arbitrarily. 

Any reason for why this could be?

**Comment by Liam-Dow** [comment]
Okay. My balance now reflects the correct amount. I'm not sure why this temporary issue occurred.

**Comment by dasource** [comment]
This is working as intended and by design. 
Should you wish to test lots of transactions please use this method: 

`for i in {1..100}; do ./particl-cli sendtoaddress <address> 1; done`
